;;; modus-themes-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from modus-operandi-deuteranopia-theme.el

(put 'modus-operandi-deuteranopia 'theme-properties '(:background-mode light :kind color-scheme :family modus))


;;; Generated autoloads from modus-operandi-theme.el

(put 'modus-operandi 'theme-properties '(:background-mode light :kind color-scheme :family modus))


;;; Generated autoloads from modus-operandi-tinted-theme.el

(put 'modus-operandi-tinted 'theme-properties '(:background-mode light :kind color-scheme :family modus))


;;; Generated autoloads from modus-operandi-tritanopia-theme.el

(put 'modus-operandi-tritanopia 'theme-properties '(:background-mode light :kind color-scheme :family modus))


;;; Generated autoloads from modus-themes.el

(autoload 'modus-themes-contrast "modus-themes" "\
Measure WCAG contrast ratio between C1 and C2.
C1 and C2 are color values written in hexadecimal RGB.

(fn C1 C2)")
(autoload 'modus-themes-select "modus-themes" "\
Load a Modus THEME using minibuffer completion.
Run `modus-themes-after-load-theme-hook' after loading the theme.
Disable other themes per `modus-themes-disable-other-themes'.

(fn THEME)" t)
(autoload 'modus-themes-toggle "modus-themes" "\
Toggle between the two `modus-themes-to-toggle'.
If `modus-themes-to-toggle' does not specify two Modus themes,
prompt with completion for a theme among our collection (this is
practically the same as the `modus-themes-select' command).

Run `modus-themes-after-load-theme-hook' after loading the theme.
Disable other themes per `modus-themes-disable-other-themes'." t)
(autoload 'modus-themes-theme "modus-themes" "\
Bind NAME's color PALETTE around face specs and variables.
Face specifications are passed to `custom-theme-set-faces'.
While variables are handled by `custom-theme-set-variables'.
Those are stored in `modus-themes-faces' and
`modus-themes-custom-variables' respectively.

Optional OVERRIDES are appended to PALETTE, overriding
corresponding entries.

(fn NAME PALETTE &optional OVERRIDES)" nil t)
(function-put 'modus-themes-theme 'lisp-indent-function 0)
(when load-file-name (let ((dir (file-name-directory load-file-name))) (unless (equal dir (expand-file-name "themes/" data-directory)) (add-to-list 'custom-theme-load-path dir))))
(register-definition-prefixes "modus-themes" '("modus-themes-"))


;;; Generated autoloads from modus-vivendi-deuteranopia-theme.el

(put 'modus-vivendi-deuteranopia 'theme-properties '(:background-mode dark :kind color-scheme :family modus))


;;; Generated autoloads from modus-vivendi-theme.el

(put 'modus-vivendi 'theme-properties '(:background-mode dark :kind color-scheme :family modus))


;;; Generated autoloads from modus-vivendi-tinted-theme.el

(put 'modus-vivendi-tinted 'theme-properties '(:background-mode dark :kind color-scheme :family modus))


;;; Generated autoloads from modus-vivendi-tritanopia-theme.el

(put 'modus-vivendi-tritanopia 'theme-properties '(:background-mode dark :kind color-scheme :family modus))

;;; End of scraped data

(provide 'modus-themes-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; modus-themes-autoloads.el ends here
