;;; .user-lisp-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from sthenno-hermit.el

(autoload 'sthenno/hermit-mode "sthenno-hermit"
"Toggle Hermit Pet mode.

This is a minor mode.  If called interactively, toggle the
`Sthenno/Hermit mode' mode.  If the prefix argument is positive, enable
the mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate the variable `sthenno/hermit-mode'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(autoload 'sthenno/hermit-start "sthenno-hermit"
"Enable `sthenno/hermit-mode'.

(fn &optional FILE PARENT)" t)
(autoload 'sthenno/hermit-stop "sthenno-hermit"
"Disable `sthenno/hermit-mode'." t)
(autoload 'sthenno/hermit-restart "sthenno-hermit"
"Restart `sthenno/hermit-mode'." t)
(autoload 'sthenno/hermit-hide "sthenno-hermit"
"Hide Hermit without disabling `sthenno/hermit-mode'." t)
(autoload 'sthenno/hermit-show "sthenno-hermit"
"Show Hermit without raising or selecting it." t)
(autoload 'sthenno/hermit-iconify-parent "sthenno-hermit"
"Iconify Hermit root parent frame." t)
(register-definition-prefixes "sthenno-hermit" '("sthenno/hermit-"))


;;; Generated autoloads from sthenno-hermit-endpoint.el

(autoload 'ear-agent-mode "sthenno-hermit-endpoint"
"Minor mode for the EAR reflective Emacs agent.

Keys:
  C-c e a  ask agent
  C-c e r  ask agent about region
  C-c e o  observe current state
  C-c e c  open chat buffer

This is a minor mode.  If called interactively, toggle the `EAR-Agent
mode' mode.  If the prefix argument is positive, enable the mode, and if
it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate the variable `ear-agent-mode'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(register-definition-prefixes "sthenno-hermit-endpoint" '("ear-agent-"))


;;; Generated autoloads from sthenno-hermit-voice.el

(autoload 'sthenno/hermit-listen "sthenno-hermit-voice"
"Toggle Hermit voice recording.
In streaming mode, the first invocation starts live transcription and the second
submits the current transcript to gptel.  In record mode, the first invocation
starts recording, and the second stops recording and runs
`sthenno/hermit-transcribe-command'." t)
(autoload 'sthenno/hermit-voice-stop "sthenno-hermit-voice"
"Stop Hermit voice recording, transcription and LLM requests." t)
(autoload 'sthenno/hermit-voice-reset-history "sthenno-hermit-voice"
"Clear Hermit's voice conversation history." t)
(register-definition-prefixes "sthenno-hermit-voice" '("sthenno/hermit-"))


;;; Generated autoloads from sthenno-yoshino.el

(autoload 'sthenno-yoshino-personality "sthenno-yoshino"
"Return Yoshino's current personality.")
(autoload 'sthenno-yoshino-reset "sthenno-yoshino"
"Reset Yoshino's in-memory state." t)
(autoload 'sthenno-yoshino-log-open "sthenno-yoshino"
"Open Yoshino's live logging buffer." t)
(autoload 'sthenno-yoshino-log-clear "sthenno-yoshino"
"Clear Yoshino's live logging buffer." t)
(autoload 'sthenno-yoshino-log-enable "sthenno-yoshino"
"Enable Yoshino's live logging buffer." t)
(autoload 'sthenno-yoshino-log-disable "sthenno-yoshino"
"Disable Yoshino's live logging buffer." t)
(autoload 'sthenno-yoshino-initialize "sthenno-yoshino"
"Create Yoshino's initial Denote notes.
This includes personality, diary, trace, memory, and reflection." t)
(autoload 'sthenno-yoshino-save-trace "sthenno-yoshino"
"Append a complete snapshot of Yoshino's in-memory trace to the trace note." t)
(autoload 'sthenno-yoshino-write-diary "sthenno-yoshino"
"Append TEXT to Yoshino's Denote diary and return the diary file.

(fn TEXT)" t)
(autoload 'sthenno-yoshino-write-memory "sthenno-yoshino"
"Append TEXT to Yoshino's Denote memory note and return the memory file.

(fn TEXT)" t)
(autoload 'sthenno-yoshino-rewrite-memory "sthenno-yoshino"
"Rewrite Yoshino's durable memory note with TEXT.

(fn TEXT)" t)
(autoload 'sthenno-yoshino-rewrite-reflection "sthenno-yoshino"
"Rewrite Yoshino's reflection note with TEXT.

(fn TEXT)" t)
(autoload 'sthenno-yoshino-write-open-async "sthenno-yoshino"
"Stream open-ended diary prose for PROMPT into Yoshino's diary.
Call CALLBACK with a result string when the stream finishes.

(fn &optional PROMPT CALLBACK)")
(autoload 'sthenno-yoshino-diary-open "sthenno-yoshino"
"Start an open-ended streaming diary request for PROMPT.

(fn PROMPT)" t)
(defalias 'sthenno-yoshino-write-open #'sthenno-yoshino-diary-open)
(autoload 'sthenno-yoshino-write-reflection "sthenno-yoshino"
"Append TEXT to Yoshino's Denote reflection note and return the file.

(fn TEXT)" t)
(autoload 'sthenno-yoshino-observe "sthenno-yoshino"
"Observe the current Emacs environment." t)
(autoload 'sthenno-yoshino-system-prompt "sthenno-yoshino"
"Return Yoshino's system prompt.")
(autoload 'sthenno-yoshino-handle-decision-async "sthenno-yoshino"
"Handle Yoshino JSON decision TEXT asynchronously, then call CALLBACK.

(fn TEXT CALLBACK)")
(autoload 'sthenno-yoshino-handle-decision "sthenno-yoshino"
"Handle Yoshino JSON decision TEXT and wait for the asynchronous action.

(fn TEXT)" t)
(autoload 'sthenno-yoshino-step "sthenno-yoshino"
"Run one Yoshino observe/request/action/reflection step." t)
(autoload 'sthenno-yoshino-loop-running-p "sthenno-yoshino"
"Return non-nil when Yoshino's background loop is running.")
(autoload 'sthenno-yoshino-loop-stop "sthenno-yoshino"
"Stop Yoshino's background loop." t)
(autoload 'sthenno-yoshino-loop-start "sthenno-yoshino"
"Start Yoshino's background memory/reflection loop.
INTERVAL is the number of seconds between loop ticks.

(fn &optional INTERVAL)" t)
(defvar sthenno-yoshino-mode nil
"Non-nil if Sthenno-Yoshino mode is enabled.
See the `sthenno-yoshino-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `sthenno-yoshino-mode'.")
(custom-autoload 'sthenno-yoshino-mode "sthenno-yoshino" nil)
(autoload 'sthenno-yoshino-mode "sthenno-yoshino"
"Toggle Yoshino diary mode.

This is a global minor mode.  If called interactively, toggle the
`Sthenno-Yoshino mode' mode.  If the prefix argument is positive, enable
the mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `(default-value \\='sthenno-yoshino-mode)'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(register-definition-prefixes "sthenno-yoshino" '("sthenno-yoshino-"))


;;; End of scraped data

(provide '.user-lisp-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; .user-lisp-autoloads.el ends here
