;;; pythonic-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from pythonic.el

(autoload 'pythonic-activate "pythonic" "\
Activate python VIRTUALENV.

(fn VIRTUALENV)" t)
(autoload 'pythonic-deactivate "pythonic" "\
Deactivate python virtual environment." t)
(register-definition-prefixes "pythonic" '("pythonic-"))

;;; End of scraped data

(provide 'pythonic-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; pythonic-autoloads.el ends here
